const COLOMBIA_LOCATIONS = {
  "Amazonas": ["Leticia", "Puerto Nariño"],
  "Antioquia": ["Medellín", "Bello", "Itagüí", "Envigado", "Apartadó", "Rionegro", "Turbo", "Caucasia", "Copacabana", "Caldas"],
  "Arauca": ["Arauca", "Arauquita", "Saravena", "Tame"],
  "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Sabanagrande", "Baranoa", "Galapa", "Puerto Colombia"],
  "Bogotá D.C.": ["Bogotá D.C."],
  "Bolívar": ["Cartagena de Indias", "Magangué", "El Carmen de Bolívar", "Turbaco", "Arjona", "Mompós"],
  "Boyacá": ["Tunja", "Sogamoso", "Duitama", "Chiquinquirá", "Puerto Boyacá", "Paipa"],
  "Caldas": ["Manizales", "La Dorada", "Chinchiná", "Villamaría", "Riosucio"],
  "Caquetá": ["Florencia", "San Vicente del Caguán", "Cartagena del Chairá", "El Paujil", "Puerto Rico"],
  "Casanare": ["Yopal", "Aguazul", "Paz de Ariporo", "Villanueva", "Tauramena", "Monterrey"],
  "Cauca": ["Popayán", "Santander de Quilichao", "El Tambo", "Puerto Tejada", "Piendamó"],
  "Cesar": ["Valledupar", "Aguachica", "Agustín Codazzi", "Bosconia", "Curumaní"],
  "Chocó": ["Quibdó", "Istmina", "Tadó", "Riosucio", "Condoto"],
  "Córdoba": ["Montería", "Lorica", "Sahagún", "Cereté", "Montelíbano", "Planeta Rica"],
  "Cundinamarca": ["Soacha", "Fusagasugá", "Facatativá", "Zipaquirá", "Chía", "Girardot", "Mosquera", "Madrid"],
  "Guainía": ["Inírida"],
  "Guaviare": ["San José del Guaviare", "El Retorno", "Calamar"],
  "Huila": ["Neiva", "Pitalito", "Garzón", "La Plata", "Campoalegre"],
  "La Guajira": ["Riohacha", "Maicao", "Uribia", "San Juan del Cesar", "Fonseca"],
  "Magdalena": ["Santa Marta", "Ciénaga", "Zona Bananera", "Fundación", "El Banco"],
  "Meta": ["Villavicencio", "Acacías", "Granada", "Puerto López", "San Martín"],
  "Nariño": ["Pasto", "Tumaco", "Ipiales", "Túquerres", "Samaniego"],
  "Norte de Santander": ["Cúcuta", "Ocaña", "Villa del Rosario", "Los Patios", "Pamplona"],
  "Putumayo": ["Mocoa", "Puerto Asís", "Orito", "Valle del Guamuez", "Villagarzón"],
  "Quindío": ["Armenia", "Calarcá", "Montenegro", "La Tebaida", "Quimbaya"],
  "Risaralda": ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia"],
  "San Andrés y Providencia": ["San Andrés", "Providencia"],
  "Santander": ["Bucaramanga", "Floridablanca", "Barrancabermeja", "Girón", "Piedecuesta", "San Gil"],
  "Sucre": ["Sincelejo", "Corozal", "San Marcos", "Tolú", "Sampués"],
  "Tolima": ["Ibagué", "Espinal", "Melgar", "Chaparral", "Honda", "Líbano"],
  "Valle del Cauca": ["Cali", "Buenaventura", "Palmira", "Tuluá", "Yumbo", "Cartago", "Jamundí", "Buga"],
  "Vaupés": ["Mitú"],
  "Vichada": ["Puerto Carreño", "La Primavera", "Cumaribo", "Santa Rosalía"]
};
